#include "gcode_gen.h"
#include <fstream>
#include <iomanip>

GCodeGen::GCodeGen(double retract, double feed) : retract_(retract), feed_(feed) {}

void GCodeGen::generateFromFeatures(const std::vector<Feature>& feats, const std::string &out_path){
    std::ofstream ofs(out_path);
    ofs << "(Generated by local fallback GCodeGen)\n";
    ofs << "G20 G90 G17 G54\n";
    ofs << "M6 T1\nS1000 M3\n";
    for(auto &f : feats){
        if(f.type == "hole"){
            ofs << "(Drill)\n";
            ofs << std::fixed << std::setprecision(4);
            ofs << "G00 X" << f.x << " Y" << f.y << "\n";
            ofs << "G01 Z-" << (f.diameter * 1.5) << " F5.0\n";
            ofs << "G00 Z" << retract_ << "\n";
        } else if(f.type == "contour"){
            ofs << "(Contour)\n";
            if(!f.contour_pts.empty()){
                // naive: move to first pt in units assume already in units
                ofs << std::fixed << std::setprecision(4);
                ofs << "G00 X" << (f.contour_pts[0].x) << " Y" << (f.contour_pts[0].y) << "\n";
                for(size_t i=1;i<f.contour_pts.size();++i){
                    ofs << "G01 X" << f.contour_pts[i].x << " Y" << f.contour_pts[i].y << " F" << feed_ << "\n";
                }
            }
        }
    }
    ofs << "M30\n";
    ofs.close();
}

void GCodeGen::writeProgramText(const std::string &program_text, const std::string &out_path){
    std::ofstream ofs(out_path);
    ofs << program_text;
    ofs.close();
}

